---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  namespace: knative-serving
  name: serving
spec:
  config:
    domain:
      vcap.me: ""
    network:
      ingress.class: kourier.ingress.networking.knative.dev
  ingress:
    kourier:
      enabled: true
